version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: <CONTAINER_NAME>
          ContainerPort: 80
        PlatformVersion: "1.4.0"
hooks:
  AfterAllowTraffic:
    - location: AfterAllowTraffic.sh
      timeout: 300
      runas: root
      environment:
        variables:
          REGION: "<ECR_REGION>"
          ECR_REPO_URI: "<ECR_REPO_URI>"
          IMAGE_TAG: "<IMAGE_TAG>"