services:
  app:
    build:
      dockerfile: app/Dockerfile
      target: development
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    environment:
      - ENV=development
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"